export const LOGIN_ORIGIN = 'LOGIN_ORIGIN';
export const LOGIN_BEFORE = 'LOGIN_BEFORE';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CHANGE_SIGNUP_AUTH = 'CHANGE_SIGNUP_AUTH';