export const FETCH_CHATDATA = 'FETCH_CHATDATA';
export const FETCH_CHATDATA_REQUEST = 'FETCH_CHATDATA_REQUEST';
export const FETCH_CHATDATA_SUCCESS = 'FETCH_CHATDATA_SUCCESS';
export const FETCH_CHATDATA_FAILURE = 'FETCH_CHATDATA_FAILURE';

export const ADD_BOT_CHATMSG = 'ADD_BOT_CHATMSG'; 
export const GET_BOT_RESPONSE = 'GET_BOT_RESPONSE';

export const CHAGNE_CROOM_ID = 'CHAGNE_CROOM_ID'; 
export const CHAGNE_PROOM_ID = 'CHAGNE_PROOM_ID';
export const CHAGNE_NOW_BOTROOM_ID = 'CHAGNE_NOW_BOTROOM_ID';

export const CLEAR_CHAT_LIST = 'CLEAR_CHAT_LIST';