export const FETCH_CHATDATA = 'FETCH_CHATDATA';
export const FETCH_CHATDATA_REQUEST = 'FETCH_CHATDATA_REQUEST';
export const FETCH_CHATDATA_SUCCESS = 'FETCH_CHATDATA_SUCCESS';
export const FETCH_CHATDATA_FAILURE = 'FETCH_CHATDATA_FAILURE';

export const ADD_TA_CHATMSG = 'ADD_TA_CHATMSG';
export const GET_TA_RESPONSE = 'GET_TA_RESPONSE';