export const FETCH_CHATDATA = 'FETCH_CHATDATA';
export const FETCH_CHATDATA_REQUEST = 'FETCH_CHATDATA_REQUEST';
export const FETCH_CHATDATA_SUCCESS = 'FETCH_CHATDATA_SUCCESS';
export const FETCH_CHATDATA_FAILURE = 'FETCH_CHATDATA_FAILURE';

export const ADD_TA_CHATMSG = 'ADD_TA_CHATMSG'; 
export const GET_TA_RESPONSE = 'GET_TA_RESPONSE';

export const ADD_TA_CHATROOM = 'ADD_TA_CHATROOM'; 
export const CHANGE_NOW_TA_CHATROOM = 'CHANGE_NOW_TA_CHATROOM'; 
export const CHANGE_ROOM_CHECKED = 'CHANGE_ROOM_CHECKED';

export const CLEAR_TACHAT_LIST = 'CLEAR_TACHAT_LIST';
export const CLEAR_TACHATROOM_LIST = 'CLEAR_TACHATROOM_LIST';

export const UPDATE_TACHATROOM_LIST = 'UPDATE_TACHATROOM_LIST';


