export const FETCH_CHATDATA = 'FETCH_CHATDATA';
export const FETCH_CHATDATA_REQUEST = 'FETCH_CHATDATA_REQUEST';
export const FETCH_CHATDATA_SUCCESS = 'FETCH_CHATDATA_SUCCESS';
export const FETCH_CHATDATA_FAILURE = 'FETCH_CHATDATA_FAILURE';

export const ADD_CHATMSG = 'ADD_CHATMSG'; 
export const GET_BOT_RESPONSE = 'GET_BOT_RESPONSE';